#!/usr/bin/env python3
# Patch: V50 -> V51  "Exportmodus sichtbar machen" (Audit-Befund N6)
#
#  V1   <title>: Versionsnummer auf V51
#  V2   <h1>: Versionsnummer auf V51
#  N6a  Hilfsfunktionen: Kopfzeilen fuer den Export, Klartext fuer Meldungen,
#       Merker fuer den Modus der Vorschau
#  N6b  Vorschau: Modus festhalten, Kopfzeilen voranstellen
#  N6c  Download: Modus der Vorschau verwenden statt die Checkbox neu zu lesen
#  N6d  Download-Meldung nennt den Modus
#  N6e  Mod-Ordner: Kopfzeilen voranstellen
#  N6f  Mod-Meldungen (Ordner und ZIP) nennen den Modus
#
# Hintergrund N6: Die Checkbox "Skip localization file" aendert den Vertrag
# der exportierten Datei. Mit ihr steht name = "Asgard" im Initializer, ohne
# sie name = "NAME_Asgard" und der Schluessel zeigt in die mitgelieferte .yml.
# Keine Datei und keine Meldung verriet bisher, welcher Modus sie erzeugt hat.
#
# Nebenbei geschlossen: Der Download las die Checkbox ein zweites Mal, statt
# den Modus der Vorschau zu uebernehmen. Das Modal hat keine Fokusfalle, per
# Tab und Leertaste liess sich die Checkbox hinter der Abdunklung umschalten.
# Ergebnis waere ein Initializer mit NAME_-Schluesseln ohne passende .yml.
#
# Die Exportdatei aendert sich damit um genau die Kopfzeilen. Alles darunter
# muss bytegleich zu V50 bleiben, geprueft mit compare_exports.py.
#
# Usage: python3 patch_v50_to_v51.py <input.html> <output.html>

import sys

if len(sys.argv) != 3:
    sys.exit("usage: patch_v50_to_v51.py <input.html> <output.html>")

SRC, DST = sys.argv[1], sys.argv[2]

with open(SRC, encoding="utf-8") as fh:
    data = fh.read()

# ---------------------------------------------------------------- V1/V2
V1_OLD = "<title>Stellaris Solar System Editor V50 - Full Editor</title>"
V1_NEW = "<title>Stellaris Solar System Editor V51 - Full Editor</title>"

V2_OLD = '<h1 class="stellaris-header">Stellaris Solar System Editor V50</h1>'
V2_NEW = '<h1 class="stellaris-header">Stellaris Solar System Editor V51</h1>'

# --------------------------------------------------------------- N6a
N6A_OLD = "        function generateSystemCode(system) {"

N6A_NEW = "\n".join([
    "        // ===== V51 N6: EXPORTMODUS SICHTBAR MACHEN =====",
    "        //",
    "        // Der Exportmodus aendert den Vertrag der Datei: Klarname inline",
    "        // oder Lokalisierungsschluessel mit passender .yml. Bisher blieb",
    "        // davon keine Spur. Jetzt steht er als Kommentar am Dateikopf.",
    "        //",
    "        // Die Kopfzeilen beginnen ausnahmslos mit #. Fuer das Spiel sind das",
    "        // Kommentare (38 von 40 Vanilla-Initializern tragen solche Zeilen).",
    "        // Fuer den eigenen Importer sind sie unsichtbar: seine Dateiebene",
    "        // erkennt nur Zeilen, die in Spalte 0 mit Bezeichner und '= {'",
    "        // beginnen. Eine Kopfzeile ohne fuehrendes # wuerde diese Garantie",
    "        // brechen, deshalb gibt es hier keine.",
    "",
    "        const EDITOR_VERSION = 'V51';",
    "",
    "        // Modus, mit dem die aktuelle Vorschau erzeugt wurde. null = keine.",
    "        let exportPreviewSkipLoc = null;",
    "",
    "        function exportModeHeader(skipLoc) {",
    "            const lines = [",
    "                '# Generated by Stellaris Solar System Editor ' + EDITOR_VERSION,",
    "                skipLoc",
    "                    ? '# Names: plain text inline. No localisation files belong to this export.'",
    "                    : '# Names: localisation keys (NAME_...). Requires the .yml files from the same export.'",
    "            ];",
    "            return lines.join('\\n') + '\\n\\n';",
    "        }",
    "",
    "        function exportModeLabel(skipLoc) {",
    "            return skipLoc ? 'plain names, no localisation' : 'localisation keys + .yml';",
    "        }",
    "",
    "        function generateSystemCode(system) {",
])

# --------------------------------------------------------------- N6b
N6B_OLD = "\n".join([
    "            const exportCode = allSystems.map(sys => generateSystemCode(sys)).join('\\n\\n');",
    "            document.getElementById('exportTextarea').value = exportCode;",
])

N6B_NEW = "\n".join([
    "            // V51 N6: Modus beim Erzeugen der Vorschau festhalten. Der",
    "            // Download uebernimmt genau diesen Text und muss deshalb auch",
    "            // genau diesen Modus fuer die .yml-Entscheidung verwenden.",
    "            exportPreviewSkipLoc = document.getElementById('skipLocalizationCheckbox').checked;",
    "            const exportCode = exportModeHeader(exportPreviewSkipLoc) +",
    "                allSystems.map(sys => generateSystemCode(sys)).join('\\n\\n');",
    "            document.getElementById('exportTextarea').value = exportCode;",
])

# --------------------------------------------------------------- N6c
N6C_OLD = "            const skipLocalization = document.getElementById('skipLocalizationCheckbox').checked;"

N6C_NEW = "\n".join([
    "            // V51 N6: nicht die Checkbox neu lesen, sondern den Modus, mit dem",
    "            // die Vorschau erzeugt wurde. Das Modal hat keine Fokusfalle, per",
    "            // Tab und Leertaste liess sich die Checkbox hinter der Abdunklung",
    "            // umschalten, und dann passten Initializer und .yml nicht zusammen.",
    "            const skipLocalization = (exportPreviewSkipLoc !== null)",
    "                ? exportPreviewSkipLoc",
    "                : document.getElementById('skipLocalizationCheckbox').checked;",
])

# --------------------------------------------------------------- N6d
N6D_OLD = ("            showNotification(`\U0001F4BE ${fileCount} file${fileCount > 1 ? 's' : ''} "
           "downloaded!`);")
N6D_NEW = ("            showNotification(`\U0001F4BE ${fileCount} file${fileCount > 1 ? 's' : ''} "
           "downloaded (${exportModeLabel(skipLocalization)}).`);")

# --------------------------------------------------------------- N6e
N6E_OLD = "\n".join([
    "            const initializerCode = allSystems.map(sys => generateSystemCode(sys)).join('\\n\\n');",
    "            const skipLoc = document.getElementById('skipLocalizationCheckbox')?.checked;",
])

N6E_NEW = "\n".join([
    "            const skipLoc = document.getElementById('skipLocalizationCheckbox')?.checked || false;",
    "            // V51 N6: Kopfzeilen mit Version und Namensmodus.",
    "            const initializerCode = exportModeHeader(skipLoc) +",
    "                allSystems.map(sys => generateSystemCode(sys)).join('\\n\\n');",
])

# --------------------------------------------------------------- N6f
N6F1_OLD = 'showNotification(`\U0001F4E6 Mod "${modName}" written to the selected folder!`, \'success\');'
N6F1_NEW = ('showNotification(`\U0001F4E6 Mod "${modName}" written to the selected folder '
            '(${exportModeLabel(skipLoc)}).`, \'success\');')

N6F2_OLD = 'showNotification(`\U0001F4E6 Mod "${modName}" downloaded as ZIP!`, \'success\');'
N6F2_NEW = ('showNotification(`\U0001F4E6 Mod "${modName}" downloaded as ZIP '
            '(${exportModeLabel(skipLoc)}).`, \'success\');')

PATCHES = [
    ("V1  Titel auf V51",                 V1_OLD,   V1_NEW,   1),
    ("V2  Ueberschrift auf V51",          V2_OLD,   V2_NEW,   1),
    ("N6a Hilfsfunktionen und Merker",    N6A_OLD,  N6A_NEW,  1),
    ("N6b Vorschau mit Kopfzeilen",       N6B_OLD,  N6B_NEW,  1),
    ("N6c Download nutzt Vorschau-Modus", N6C_OLD,  N6C_NEW,  1),
    ("N6d Download-Meldung mit Modus",    N6D_OLD,  N6D_NEW,  1),
    ("N6e Mod-Ordner mit Kopfzeilen",     N6E_OLD,  N6E_NEW,  1),
    ("N6f Mod-Meldung Ordner",            N6F1_OLD, N6F1_NEW, 1),
    ("N6f Mod-Meldung ZIP",               N6F2_OLD, N6F2_NEW, 1),
]

for name, old, new, expected in PATCHES:
    found = data.count(old)
    assert found == expected, f"{name}: erwartet {expected} Fundstelle(n), gefunden {found}"
    assert data.count(new) == 0, f"{name}: Ersetzung liegt bereits vor, Abbruch"
    data = data.replace(old, new, expected)
    print(f"  ok  {name}")

with open(DST, "w", encoding="utf-8") as fh:
    fh.write(data)

print(f"geschrieben: {DST}")
